# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9bd84662473c493e49ff661dede040b9df3debff168700c07ec8be89743432fcd7245e1f1723d9bf3ca7a6194a2e8646f6958cab9fac9a8b1d3ca2865851042

test:
  secret_key_base: bcd6b39e837a2e32c18cbcddefdae4a3abe44fec3eb29021f04d0bab796309e8142f22632cd676a1d441d60dfb4c6572e879f523dd1e2c96c251936d594d228b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: bcd6b39e837a2e32c18cbcddefdae4a3abe44fec3eb29021f04d0bab796309e8142f22632cd676a1d441d60dfb4c6572e879f523dd1e2c96c251936d594d248b
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
